name: backend

on:
  push: 
    branches: 
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: uses actions/checkout@v3
      - run: uses actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm test
      - run: npm build