name: backend

on:
  push: 
    branches: 
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm test -- --coverage
      - run: npm run build

      - run: node dist/index.js &
      - run: npx wait-on -t 10000 http://localhost:8080/api/health
      - run: npm run test:api

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/**
          retention-days: 5

  deploy:
    needs: build
    if: github.event.name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: rsync -v -e 'ssh -i ~/.ssh/0317.pem' dist/index.js ec2-user@35.78.115.211:~/index.js
      - run: ssh -i ~/.ssh/0317.pem ec2-user@35.78.115.211 sudo systemctl restart backend       
      - run: ssh -i ~/.ssh/0317.pem ec2-user@35.78.115.211 sudo systemctl status backend        