name: backend

on:
  push: 
    branches: 
      - main

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm test -- --coverage
      - run: npm run build

      - run: node dist/index.html &
      - run: npx wait-on -t 10000 http://localhost:8080/api/health
      - run: npm run test:api

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/**
          retention-days: 5          